### ISSUE TITLE
List of small fixes and issues

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/FunOres#15]
Hi, great mod for adding basic "mod ores" into Minecraft. Seems every mod author for 1.10 was like, "Since there are so many copies of these ores I have removed them from my mod," and now there are NO new ores! :P

I have a pretty big list of stuff for you though and I think it would make your mod even better if you added/fixed them.

Bugs:
- Iron nuggets/dust and gold dust don't show up in JEI.
- Buckets of liquid platinum/titanium and fluid blocks have broken item names
- Metal and alloy furnace aren't craftable?!

Now about disabling items: I pretty much only use this mod for metal ores for now. When disabling the mob ores they still show up in JEI. You said disabling items would cause them to not appear but "they will still exist." That's not ideal. For example, metals still appears in the creative menu even though they are disabled and even though hidden from JEI.
Please when an item is disabled simply do not register it at all. It is much more effective and clean and reduces headaches when trying to be compatible with other mods. If the user wants to disable an item it should not exist at all. Forge warns users that loading a world will remove any instances of a certain block/item so users that disable items will be aware.
Also I should mention that not every item is allowed to be disabled. There should be a configuration to disable anything the mod registers. I honestly think all mods should do this and you are on the right track for sure. But not every item is listed in the config for example the machines, (Yes, they should be allowed to be disabled even if it causes no way to make certain alloys) the drying rack, and vanilla elements. What I mean by 'vanilla elements' is for example I can disable iron/gold plates and gears but not iron/gold dust or iron nuggets. (You can't disable gold nuggets obviously)

Thanks for reading and I hope you can fix these things. It would make your mod the perfect, exactly and perfectly customizable base ore mod for 1.10.2!  :)

**Comment by SilentChaos512** [comment]
I think I can fix most, if not all of, these issues. Not registering disabled blocks/items is not really possible though, since I rely heavily on metadata-based blocks/items. For example, a copper ingot is the same item as a tin ingot, just with different metadata. I can't just not register one, but I could probably make some adjustments to minimize how many places they show up. I've received criticism in the past for using metadata items, but that's how I've always done it. It's good for organization and was especially helpful in the past when ID conflicts had to be fixed by hand... Those were tough times.

So just for reference, disabling something should:
- Not register the recipe(s) to craft it, so it is unobtainable.
- Not register it in the ore dictionary, so it does not show up in recipes.
- Hide it in JEI.
- Remove it from the sub-items list, so it will not appear in creative tabs.
- Possibly not register the block/item, _if_ all sub-blocks or sub-items are disabled.

For your bug list:
- Looks like I broke that when adding the item disable feature... Easy fix
- Probably just didn't care enough at the time to check... That was just a quick compatibility thing for people who play with TCon (I don't). Probably an easy fix.
- They are craftable... provided you haven't disabled the plates required to craft them :p. Disabling plates removes their ore dictionary entries too, so it breaks the recipes.

List of things I need to do:
- [x] **Hide disabled items in creative tabs** by modifying the getSubItems method of _every block and item_. Or create a special Item class with some shared IDisableable code to reduce copy-paste.
- [x] **Add hiding feature for disabled ores**. They currently are not hidden because ore "disabling" was done before people started asking for ways to completely remove the things they don't want.
- [x] **Add disable configs for _everything_**. This will likely take a few tries to get completely right, since parts of the code is on an item-by-item basis... As much as I've tried to automate the disabling of items, it's still a bit tricky.
- [x] **Make sure all extended vanilla (iron/gold) items are functioning correctly**. They can be a bit finicky because of how they are tacked on to the items for basic mod metals.
- [ ] **Fix fluid localization**.

Let me know if I missed anything on that list. I'll try to get some work done on this sometime this week if I can find time.

**Comment by ghost** [comment]
I guess I disabled plates so I couldn't craft the machines. xD But I would like to disable them since I use EnderIO alloy smelter.

Yes your list looks correct. Your practices as a mod dev are excellent. You answered all my questions in detail promptly and offered to fix and add the features. You should make other mods :)

**Comment by SilentChaos512** [comment]
Thanks, I try to at least respond to comments/issues and fix major bugs quickly. Oh, and I do make [some other mods](https://minecraft.curseforge.com/members/SilentChaos512/projects), the most notable being Silent's Gems.

**Comment by SilentChaos512** [comment]
Would you be able to upload a copy of your config file for me?
