### ISSUE TITLE
[error log] Could not parse "0.025" as float

### ISSUE THREAD

**Issue by drakray** [SilentChaos512/FunOres#18]
I got these warning every time I load a world, using default config

[CHAT] [FunOres] You have 10 malformed item drop keys in your config file! They will not work unless fixed!
[CHAT] [FunOres] Could not parse "0.025" as float: minecraft:saddle 1 0 0.025 0.010 0.000
[CHAT] [FunOres] Could not parse "0.150" as float: minecraft:egg 2 0 0.150 0.020 0.700
[CHAT] [FunOres] Could not parse "1.000" as float: minecraft:wool 1 12 1.000 0.000 0.500
[CHAT] [FunOres] Could not parse "1.000" as float: FunOres:Shard 1 0 1.000 0.000 0.700
[CHAT] [FunOres] Could not parse "0.100" as float: FunOres:Shard 1 0 0.100 0.000 0.400
[CHAT] [FunOres] Could not parse "0.005" as float: minecraft:sponge 1 0 0.005 0.001 0.000
[CHAT] [FunOres] Could not parse "1.000" as float: FunOres:Shard 1 2 1.000 0.000 0.700
[CHAT] [FunOres] Could not parse "0.250" as float: FunOres:Shard 1 2 0.250 0.000 0.400
[CHAT] [FunOres] Could not parse "1.000" as float: FunOres:Shard 1 1 1.000 0.000 0.700
[CHAT] [FunOres] Could not parse "0.100" as float: FunOres:Shard 1 1 0.100 0.000 0.400

any idea why that is?

**Comment by SilentChaos512** [comment]
Try deleting the config file for Fun Ores. If that doesn't fix it, I need to know what version of Minecraft, Forge, and Fun Ores you are using.

**Comment by drakray** [comment]
Still got the message after deleting FunOres.cfg

MC 1.10.2
Forge 2125
FunOres 1.3.2-76
- a bunch of mod listed in file bellow
  [Full latest.log](http://pastebin.com/ScfjGKnD)

**Comment by SilentChaos512** [comment]
Do you know what your current system locale is?

**Comment by drakray** [comment]
English(Canada), dot for decimal
something weird happened, I installed BiomesOPlenty, Better Agriculture and Natura w/ Mantle, and the message are gone(I also updated a couple of other mods).
I still don't see brown wool in JER though

**Comment by SilentChaos512** [comment]
Not really sure why this is happening. If you can still reproduce this issue, try this build of the mod and let me know if it fixes the problem: [FunOres-1.10.2-1.3.3-78.jar.zip](https://github.com/SilentChaos512/FunOres/files/590862/FunOres-1.10.2-1.3.3-78.jar.zip) (be sure to extract the JAR from the ZIP file or it won't work!)

I don't think any ores from this mod are compatible with JER. Not sure if that's because of the unusual way the ores work, or if there's something I need to do to make it work.
