### ISSUE TITLE
Won't Even Boot Up Game-Goob

### ISSUE THREAD

**Issue by TheGooblyGoob** [SilentChaos512/FunOres#30]
[crash-2017-05-05_11.41.22-client.txt](https://github.com/SilentChaos512/FunOres/files/979746/crash-2017-05-05_11.41.22-client.txt)

**Comment by SilentChaos512** [comment]
Nothing in the crash report seems to indicate it's Fun Ores, seems to be a mod called "Better Grass"? I don't see it in the mod list for whatever reason, but I do see a class called "BetterGrass" (line 19 of your crash report).

(edit) I just noticed you have OptiFine, so that could be causing your crash as well.

You also need to update Silent Lib. The ancient 1.2.0 version you are using won't even work with the latest versions of my mods. Update Silent Lib to 2.1.2.

**Comment by TheGooblyGoob** [comment]
Okay thank you. I don't have that mod but it could be Biomes O' Plenty. I really appreciate your help and you being really close knit with the folks who download your mod.

**Comment by SilentChaos512** [comment]
Check OptiFine as well, I know they have a Better Grass feature.

**Comment by TheGooblyGoob** [comment]
That update to silent lib fixed it

**Comment by SilentChaos512** [comment]
Alright, good to hear.

**Comment by TheGooblyGoob** [comment]
Thanks for the help!
