### ISSUE TITLE
JSON Ore Configs

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/FunOres#38]
The existing ore config is alright, but it's nothing compared to the flexibility of some mods. I don't want CustomOreGen levels of configurability, but more options would be nice. Using a JSON file would be best, that way options could be added or changed without much difficulty. Maybe even allow multiple files, so that users can literally drag and drop new ore deposits into their setup?

Feature Ideas:
- Fully customizable ore deposits. Add or remove additional veins by adding more JSON elements, even spawning in blocks from other mods or multiple vein types of the same block.
- Better biome control. Specify multiple lists of different types, instead of being limited to just one type (blacklist/whitelist/favors/avoids). Set favors/avoids multipliers for each list.
- New vein types. Some ideas include vertical stripe veins, stalactites, stalagmites, and "gravel" piles. Maybe an option to "coat" a vein with another block?

Will need a separate file to control ore properties, such as drops. I could also throw in other settings, like block hardness, harvest level, etc.

This will require a good bit of work, and I can't guarantee all ideas will make it to release. Just wanted to write this down so I don't forget.

**Comment by Zygus42** [comment]
Was going to start my own feature request, but think it will work as part of this one.

What I would like to be able to do is have multiple dimensions and set the spawn of ore in each.  For example, the Overworld, The Twilight Forest and the Lost World dimension.  Want to have Magic and Early Tech ores in the Twilight Forest but very little Iron or later ores, and then have Late Tech ores (Uranium and such) in the Lost Worlds city dimension.  So you would need a setting for the dimension, but also the ability to have multiple configs for the same type of ore so that for example you can have different amounts of iron in each dimension.

Together with your first point above, this would also allow you to set up ores spawning in Netherrack or End Stone for the Nether and End dimensions.
