### ISSUE TITLE
Ore Gen Feature

### ISSUE THREAD

**Issue by LILL097** [SilentChaos512/FunOres#61]
## What Should Be Added or Changed?

Could you pls add a config file to disable ore gen? I'd like to keep in my modpack only ghast and blaze ore gen, I used ore tweaker mod to disable the others but it didn't work...

## Why Should This Be Done?

This feature could be really useful and helpful for modpack makers and also for modmakers (like ore tweaker mod maker or ore unifying mods)

**Comment by SilentChaos512** [comment]
There are already options for this in the config file.

**Comment by LILL097** [comment]
where are those? i only saw the relative options for each ore, but not a general config file. I also tried to disable those one by one by replacing the values: glass as filler and -1 for all the other parameters. it still didn't work...

**Comment by SilentChaos512** [comment]
My bad, I forgot how the config files were. Been a long time since I worked on this mod, haha...

Have you read the wiki? (https://github.com/SilentChaos512/FunOres/wiki/Ore-Configs). You can just delete the files you don't want, as long as you leave at least one in the folder. Otherwise, setting `size` to 0 should work.
